# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (c) 2026, Tulio A M Mendes <tadryanom@hotmail.com>
# All rights reserved.
# See LICENSE for details.
#
# Source: https://github.com/tadryanom/AdrOS
#
# Makefile for initrd_init (early /init for root handoff)

NAME := initrd_init
SRCS := initrd_init.c
include ../common.mk
