// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright (c) 2018, Tulio A M Mendes <tadryanom@hotmail.com>
 * All rights reserved.
 * See LICENSE for details.
 *
 * Source: https://github.com/tadryanom/AdrOS
 */

#ifndef SYSCALL_H
#define SYSCALL_H

#include <stdint.h>

struct registers;
void syscall_init(void);
void syscall_handler(struct registers* regs);

enum {
    SYSCALL_WRITE = 1,
    SYSCALL_EXIT  = 2,
    SYSCALL_GETPID = 3,

    SYSCALL_OPEN  = 4,
    SYSCALL_READ  = 5,
    SYSCALL_CLOSE = 6,

    SYSCALL_WAITPID = 7,

    SYSCALL_LSEEK = 9,
    SYSCALL_FSTAT = 10,
    SYSCALL_STAT = 11,

    SYSCALL_DUP = 12,
    SYSCALL_DUP2 = 13,
    SYSCALL_PIPE = 14,
    SYSCALL_PIPE2 = 34,
    SYSCALL_EXECVE = 15,
    SYSCALL_FORK = 16,
    SYSCALL_GETPPID = 17,
    SYSCALL_POLL = 18,
    SYSCALL_KILL = 19,
    SYSCALL_SELECT = 20,
    SYSCALL_IOCTL = 21,
    SYSCALL_SETSID = 22,
    SYSCALL_SETPGID = 23,
    SYSCALL_GETPGRP = 24,

    SYSCALL_SIGACTION = 25,
    SYSCALL_SIGPROCMASK = 26,
    SYSCALL_SIGRETURN = 27,

    SYSCALL_MKDIR = 28,
    SYSCALL_UNLINK = 29,

    SYSCALL_GETDENTS = 30,

    SYSCALL_FCNTL = 31,

    SYSCALL_CHDIR = 32,
    SYSCALL_GETCWD = 33,
    SYSCALL_DUP3 = 35,

    SYSCALL_OPENAT = 36,
    SYSCALL_FSTATAT = 37,
    SYSCALL_UNLINKAT = 38,

    SYSCALL_RENAME = 39,
    SYSCALL_RMDIR = 40,

    SYSCALL_BRK = 41,
    SYSCALL_NANOSLEEP = 42,
    SYSCALL_CLOCK_GETTIME = 43,
    SYSCALL_MMAP = 44,
    SYSCALL_MUNMAP = 45,

    SYSCALL_SHMGET = 46,
    SYSCALL_SHMAT  = 47,
    SYSCALL_SHMDT  = 48,
    SYSCALL_SHMCTL = 49,

    SYSCALL_CHMOD  = 50,
    SYSCALL_CHOWN  = 51,
    SYSCALL_GETUID = 52,
    SYSCALL_GETGID = 53,

    SYSCALL_LINK     = 54,
    SYSCALL_SYMLINK  = 55,
    SYSCALL_READLINK = 56,

    SYSCALL_SET_THREAD_AREA = 57,

    SYSCALL_SOCKET    = 58,
    SYSCALL_BIND      = 59,
    SYSCALL_LISTEN    = 60,
    SYSCALL_ACCEPT    = 61,
    SYSCALL_CONNECT   = 62,
    SYSCALL_SEND      = 63,
    SYSCALL_RECV      = 64,
    SYSCALL_SENDTO    = 65,
    SYSCALL_RECVFROM  = 66,

    SYSCALL_CLONE     = 67,
    SYSCALL_GETTID    = 68,

    SYSCALL_FSYNC     = 69,
    SYSCALL_FDATASYNC = 70,
    SYSCALL_SIGPENDING = 71,
    SYSCALL_PREAD     = 72,
    SYSCALL_PWRITE    = 73,
    SYSCALL_ACCESS    = 74,
    SYSCALL_UMASK     = 75,
    SYSCALL_SETUID    = 76,
    SYSCALL_SETGID    = 77,
    SYSCALL_TRUNCATE  = 78,
    SYSCALL_FTRUNCATE = 79,
    SYSCALL_SIGSUSPEND = 80,
    SYSCALL_READV     = 81,
    SYSCALL_WRITEV    = 82,
    SYSCALL_ALARM     = 83,
    SYSCALL_TIMES     = 84,
    SYSCALL_FUTEX     = 85,
    SYSCALL_SIGALTSTACK = 86,
    SYSCALL_FLOCK     = 87,
    SYSCALL_GETEUID   = 88,
    SYSCALL_GETEGID   = 89,
    SYSCALL_SETEUID   = 90,
    SYSCALL_SETEGID   = 91,
    SYSCALL_SETREUID  = 92,
    SYSCALL_SETREGID  = 93,
    SYSCALL_SETITIMER  = 94,
    SYSCALL_GETITIMER  = 95,
    SYSCALL_WAITID     = 96,
    SYSCALL_SIGQUEUE   = 97,
    SYSCALL_POSIX_SPAWN = 98,
    SYSCALL_MQ_OPEN     = 99,
    SYSCALL_MQ_CLOSE    = 100,
    SYSCALL_MQ_SEND     = 101,
    SYSCALL_MQ_RECEIVE  = 102,
    SYSCALL_MQ_UNLINK   = 103,
    SYSCALL_SEM_OPEN    = 104,
    SYSCALL_SEM_CLOSE   = 105,
    SYSCALL_SEM_WAIT    = 106,
    SYSCALL_SEM_POST    = 107,
    SYSCALL_SEM_UNLINK  = 108,
    SYSCALL_SEM_GETVALUE = 109,
    SYSCALL_GETADDRINFO  = 110,
    SYSCALL_DLOPEN       = 111,
    SYSCALL_DLSYM        = 112,
    SYSCALL_DLCLOSE      = 113,

    SYSCALL_EPOLL_CREATE = 114,
    SYSCALL_EPOLL_CTL    = 115,
    SYSCALL_EPOLL_WAIT   = 116,

    SYSCALL_INOTIFY_INIT     = 117,
    SYSCALL_INOTIFY_ADD_WATCH = 118,
    SYSCALL_INOTIFY_RM_WATCH  = 119,

    SYSCALL_SENDMSG  = 120,
    SYSCALL_RECVMSG  = 121,

    SYSCALL_PIVOT_ROOT = 122,

    SYSCALL_AIO_READ    = 123,
    SYSCALL_AIO_WRITE   = 124,
    SYSCALL_AIO_ERROR   = 125,
    SYSCALL_AIO_RETURN  = 126,
    SYSCALL_AIO_SUSPEND = 127,

    SYSCALL_MOUNT = 128,

    SYSCALL_GETTIMEOFDAY = 129,
    SYSCALL_MPROTECT     = 130,
    SYSCALL_GETRLIMIT    = 131,
    SYSCALL_SETRLIMIT    = 132,
    SYSCALL_SETSOCKOPT   = 133,
    SYSCALL_GETSOCKOPT   = 134,
    SYSCALL_SHUTDOWN     = 135,
    SYSCALL_GETPEERNAME  = 136,
    SYSCALL_GETSOCKNAME  = 137,
    SYSCALL_UNAME        = 138,
    SYSCALL_GETRUSAGE    = 139,
    SYSCALL_UMOUNT2      = 140,
    SYSCALL_WAIT4        = 141,
    SYSCALL_MADVISE      = 142,
    SYSCALL_EXECVEAT     = 143,
    SYSCALL_REBOOT       = 144,
};

#endif
