#ifndef SYSCALL_H
#define SYSCALL_H

#include <stdint.h>

void syscall_init(void);

enum {
    SYSCALL_WRITE = 1,
    SYSCALL_EXIT  = 2,
    SYSCALL_GETPID = 3,

    SYSCALL_OPEN  = 4,
    SYSCALL_READ  = 5,
    SYSCALL_CLOSE = 6,

    SYSCALL_WAITPID = 7,

    SYSCALL_LSEEK = 9,
    SYSCALL_FSTAT = 10,
    SYSCALL_STAT = 11,

    SYSCALL_DUP = 12,
    SYSCALL_DUP2 = 13,
    SYSCALL_PIPE = 14,
    SYSCALL_PIPE2 = 34,
    SYSCALL_EXECVE = 15,
    SYSCALL_FORK = 16,
    SYSCALL_GETPPID = 17,
    SYSCALL_POLL = 18,
    SYSCALL_KILL = 19,
    SYSCALL_SELECT = 20,
    SYSCALL_IOCTL = 21,
    SYSCALL_SETSID = 22,
    SYSCALL_SETPGID = 23,
    SYSCALL_GETPGRP = 24,

    SYSCALL_SIGACTION = 25,
    SYSCALL_SIGPROCMASK = 26,
    SYSCALL_SIGRETURN = 27,

    SYSCALL_MKDIR = 28,
    SYSCALL_UNLINK = 29,

    SYSCALL_GETDENTS = 30,

    SYSCALL_FCNTL = 31,

    SYSCALL_CHDIR = 32,
    SYSCALL_GETCWD = 33,
    SYSCALL_DUP3 = 35,
};

#endif
